source 'https://rubygems.org'

gem 'rails', '3.2.13'

gem 'stormpath-omniauth', '1.0.0.beta.3'
gem 'stormpath-rails', '1.0.0.beta.2'

group :test, :development do
  gem 'rspec-rails', '~> 2.13.0'
  gem 'sqlite3'
  gem 'jquery-rails'
  gem 'capybara'
  gem 'pry'
  gem 'pry-debugger'
end

group :test do
  gem 'webmock'
  gem 'vcr'
end
