source 'https://rubygems.org'

gem 'stormpath-sdk', :github => 'stormpath/stormpath-sdk-ruby', :branch => 'development'
gem 'stormpath-omniauth', git: 'git://github.com/stormpath/stormpath-omniauth', branch: 'development'

gem 'sinatra'
gem 'rack-flash3'

gem 'pry'
gem 'pry-debugger'
