source 'https://rubygems.org'

gem 'activesupport'
gem 'stormpath-sdk', '1.0.0.beta.7'
gem "stormpath-omniauth", "~> 1.0.0.beta.3"

gem 'roda'
gem 'tilt'
gem 'erubis'

gem 'roda-bin', group: :development

gem 'pry', group: :development
# gem 'pry-debugger', group: :development
gem 'pry-byebug', group: :development
