source 'https://rubygems.org'

gem 'stormpath-sdk', :github => 'stormpath/stormpath-sdk-ruby', :branch => 'development'
gem 'stormpath-rails', :github => 'stormpath/stormpath-rails', :branch => 'development'

gem 'rails', '3.2.13'
gem 'sqlite3'
gem 'jquery-rails'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

group :test, :development do
  gem "rspec-rails", "~> 2.0"
  gem 'pry-debugger'
end
